
CREATE EXTENSION IF NOT EXISTS pg_stat_statements CASCADE;

CREATE EXTENSION IF NOT EXISTS columnar CASCADE;

CREATE EXTENSION IF NOT EXISTS pg_partman CASCADE;

CREATE EXTENSION IF NOT EXISTS pg_cron CASCADE;

CREATE EXTENSION IF NOT EXISTS postgres_fdw CASCADE;

CREATE EXTENSION IF NOT EXISTS redis_fdw CASCADE;

CREATE EXTENSION IF NOT EXISTS wrappers CASCADE;

CREATE EXTENSION IF NOT EXISTS multicorn CASCADE;



CREATE EXTENSION IF NOT EXISTS clerk_fdw CASCADE;
