services:
  notebook:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8888:8888
    volumes:
      - .:/app
    command: uv run jupyter notebook --allow-root --ip 0.0.0.0 --NotebookApp.token=''
  postgres:
    image: quay.io/tembo/vectorize-pg:latest
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
