[package]
name = "benchmark-target-http-postgres"
version = "0.0.1-alpha"
edition = "2018"
publish = false
authors = ["CoreDB.io"]
description = "Benchmarking running a webserver as a postgres extension"
homepage = "https://www.coredb.io"
license = "MIT"
readme = "README.md"
repository = "https://github.com/CoreDB-io/coredb"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
actix-web = "4.2.1"
actix-rt = "2.7.0"
chrono = { version = "0.4.23", features = ["serde"] }
dotenv = "0.15.0"
diesel = { version = "2.0.2", features = ["postgres", "r2d2", "uuid", "chrono"] }
diesel_migrations = "2.0.0"
env_logger = "0.10.0"
lazy_static = "1.4"
listenfd = "1.0.0"
serde = "1.0.152"
serde_json = "1.0.91"
r2d2 = "0.8.10"
uuid = { version = "1.2.2", features = ["serde", "v4"] }
