[tool.poetry]
name = "bench"
version = "0.1.0"
description = ""
authors = ["Adam Hendel <adam@coredb.io>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
locust = "^2.14.0"
pandas = "^1.5.2"
jupyter = "^1.0.0"
matplotlib = "^3.6.2"
gunicorn = "^20.1.0"
fastapi = "^0.88.0"
uvicorn = {extras = ["standard"], version = "^0.20.0"}
sqlalchemy = "^1.4.45"
psycopg2-binary = "^2.9.5"
python-dotenv = "^0.21.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
