
CREATE EXTENSION IF NOT EXISTS pg_stat_statements CASCADE;



CREATE EXTENSION IF NOT EXISTS pgmq CASCADE;

CREATE EXTENSION IF NOT EXISTS pg_partman CASCADE;

CREATE EXTENSION IF NOT EXISTS pg_jsonschema CASCADE;
