[package]
name = "trunk-registry"
version = "0.1.0"
edition = "2021"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4.3.1"
actix-cors = "0.6.4"
actix-multipart = "0.6.0"
anyhow = "1.0.69"
sqlx = { version = "0.6.2", features = [ "json", "runtime-tokio-native-tls" , "postgres", "time", "offline" ] }
url = "2.3.1"
thiserror = "1.0.39"
log = "0.4.17"
semver = { version = "1.0.16", features = ["serde"] }
serde = { version = "1.0.154", features = ["derive"] }
futures = "0.3.26"
serde_json = "1.0.94"
chrono = "0.4.23"
dotenv = "0.15.0"
env_logger = "0.10.0"
reqwest = "0.11.14"
aws-config = "0.55.0"
aws-sdk-s3 = "0.25.0"
