apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "tembo-ai.fullname" . }}-service
  labels:
    {{- include "tembo-ai.inferenceService.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.inferenceService.replicaCount }}
  selector:
    matchLabels:
      {{- include "tembo-ai.inferenceService.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.inferenceService.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "tembo-ai.inferenceService.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.inferenceService.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "tembo-ai.inferenceService.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.inferenceService.podSecurityContext | nindent 8 }}
      containers:
        - name: inference-service
          securityContext:
            {{- toYaml .Values.inferenceService.securityContext | nindent 12 }}
          image: "{{ .Values.inferenceService.image.repository }}:{{ .Values.inferenceService.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.inferenceService.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.inferenceService.service.port }}
              protocol: TCP
          {{- if and .Values.inferenceService.podMonitor.enabled (ne .Values.inferenceService.podMonitor.port "http") }}
            - name: {{ .Values.inferenceService.podMonitor.portName }}
              containerPort: {{ .Values.inferenceService.podMonitor.containerPort }}
              protocol: TCP
          {{- end }}
          {{- if .Values.inferenceService.livenessProbe.enabled }}
          livenessProbe:
            httpGet:
              path: {{ .Values.inferenceService.livenessProbe.path }}
              port: {{ .Values.inferenceService.livenessProbe.port }}
          {{- end }}
          {{- if .Values.inferenceService.readinessProbe.enabled }}
          readinessProbe:
            httpGet:
              path: {{ .Values.inferenceService.readinessProbe.path }}
              port: {{ .Values.inferenceService.readinessProbe.port }}
          {{- end }}
          resources:
            {{- toYaml .Values.inferenceService.resources | nindent 12 }}
          {{- with .Values.inferenceService.args }}
          args:
            {{- toYaml . | nindent 10 }}
          {{- end }}
          {{- with .Values.inferenceService.command }}
          command:
            {{- toYaml . | nindent 10 }}
          {{- end }}
          {{- with .Values.inferenceService.env }}
          env:
            {{- toYaml . | nindent 10 }}
          {{- end }}
      {{- with .Values.inferenceService.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.inferenceService.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.inferenceService.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
