{{- if .Values.inferenceService.services }}
{{- $defaults := .Values.inferenceService.defaults }}
{{- range $serviceName, $serviceConfig := .Values.inferenceService.services }}
{{- $mergedConfig := fromYaml (include "tembo-ai.mergeConfigs" (dict "defaults" $defaults "service" $serviceConfig)) }}
{{- if and (default false $mergedConfig.enabled) $mergedConfig.externalSecrets.secretName }}
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "tembo-ai.fullname" $ }}-{{ $serviceName }}
  namespace: {{ include "tembo-ai.namespace" $ }}
  labels:
    {{- include "tembo-ai.inferenceService.labels" . | nindent 4 }}
spec:
  refreshInterval: {{ $mergedConfig.externalSecrets.refreshInterval }}
  secretStoreRef:
    name: {{ $mergedConfig.externalSecrets.parameterStore.name }}
    kind: {{ $mergedConfig.externalSecrets.parameterStore.kind }}
  target:
    creationPolicy: 'Owner'
    name: {{ $mergedConfig.externalSecrets.secretName }}
  dataFrom:
  - find:
      name:
        regexp: {{ $mergedConfig.externalSecrets.secretRegex }}
{{- end }}
{{- end }}
{{- end }}
