{{- range $service := .Values.inferenceService }}
  {{- $externalSecrets := default (index $.Values.inferenceService 0).externalSecrets $service.externalSecrets }}
  {{- if $externalSecrets.secretName }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "tembo-ai.fullname" $ }}-{{ $service.name | default "default-service" }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "tembo-ai.inferenceService.labels" $ | nindent 4 }}
spec:
  refreshInterval: {{ $externalSecrets.refreshInterval }}
  secretStoreRef:
    name: {{ $externalSecrets.parameterStore.name }}
    kind: {{ $externalSecrets.parameterStore.kind }}
  target:
    creationPolicy: 'Owner'
    name: {{ $externalSecrets.secretName }}
  dataFrom:
  - find:
      name:
        regexp: {{ $externalSecrets.secretRegex }}
  {{- end }}
{{- end }}
