{{- range $service := .Values.inferenceService }}
  {{- if (default false $service.podMonitor.enabled) }}
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: {{ include "tembo-ai.fullname" $ }}-{{ $service.name | default "default-service" }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "tembo-ai.inferenceService.labels" $ | nindent 4 }}
spec:
  podMetricsEndpoints:
    - path: {{ default (index $.Values.inferenceService 0).podMonitor.path $service.podMonitor.path }}
      port: {{ default (index $.Values.inferenceService 0).podMonitor.portName $service.podMonitor.portName }}
  namespaceSelector:
    matchNames:
      - {{ $.Release.Namespace }}
  selector:
    matchLabels:
      {{- include "tembo-ai.inferenceService.selectorLabels" $ | nindent 6 }}
  {{- end }}
{{- end }}
