{{- if .Values.inferenceService.services }}
{{- $defaults := .Values.inferenceService.defaults }}
{{- $releaseName := default "release-name" .Release.Name }}
{{- range $serviceName, $serviceConfig := .Values.inferenceService.services }}
{{- $mergedConfig := fromYaml (include "tembo-ai.mergeConfigs" (dict "defaults" $defaults "service" $serviceConfig)) }}
{{- if and (default false $mergedConfig.enabled) (default false $mergedConfig.podMonitor.enabled) }}
---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: {{ include "tembo-ai.fullname" $ }}-{{ $serviceName }}
  namespace: {{ include "tembo-ai.namespace" $ }}
  labels:
    {{- include "tembo-ai.inferenceService.labels" . | nindent 4 }}
spec:
  podMetricsEndpoints:
  - port: {{ $mergedConfig.podMonitor.portName }}
    path: {{ $mergedConfig.podMonitor.path }}
    {{- with $mergedConfig.podMonitor.interval }}
    interval: {{ . }}
    {{- end }}
    {{- with $mergedConfig.podMonitor.scrapeTimeout }}
    scrapeTimeout: {{ . }}
    {{- end }}
  namespaceSelector:
    matchNames:
      - {{ include "tembo-ai.namespace" $ }}
  selector:
    matchLabels:
      {{- include "tembo-ai.inferenceService.selectorLabels" $ | nindent 6 }}
{{- end }}
{{- end }}
{{- end }}
