{{- if .Values.inferenceService.services }}
  {{- $defaults := .Values.inferenceService.defaults }}
  {{- range $serviceName, $serviceConfig := .Values.inferenceService.services }}
    {{- $mergedConfig := fromYaml (include "tembo-ai.inferenceService.deepMerge" (list $defaults $serviceConfig)) }}
    {{- if and (default false $mergedConfig.enabled) (default true $mergedConfig.serviceAccount.create) }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "tembo-ai.inferenceService.serviceAccountName" $ }}-{{ $serviceName }}
  namespace: {{ include "tembo-ai.namespace" $ }}
  labels:
    {{- include "tembo-ai.inferenceService.labels" $ | nindent 4 }}
    app.kubernetes.io/component: {{ $serviceName }}
  {{- with $mergedConfig.serviceAccount.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with $mergedConfig.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- if $mergedConfig.serviceAccount.imagePullSecrets }}
imagePullSecrets:
  {{- toYaml $mergedConfig.serviceAccount.imagePullSecrets | nindent 2 }}
{{- end }}
{{- if hasKey $mergedConfig.serviceAccount "automountServiceAccountToken" }}
automountServiceAccountToken: {{ $mergedConfig.serviceAccount.automountServiceAccountToken }}
{{- end }}
    {{- end }}
  {{- end }}
{{- end }}
