apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "tembo-ai.inferenceService.serviceAccountName" . }}
  labels:
    {{- include "tembo-ai.inferenceService.labels" . | nindent 4 }}
  {{- with .Values.inferenceService.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
