{{- if .Values.inferenceService.services }}
{{- $defaults := .Values.inferenceService.defaults }}
{{- range $serviceName, $serviceConfig := .Values.inferenceService.services }}
{{- $mergedConfig := fromYaml (include "tembo-ai.mergeConfigs" (dict "defaults" $defaults "service" $serviceConfig)) }}
{{- if and (default false $mergedConfig.enabled) (default true $mergedConfig.service.enabled) }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "tembo-ai.fullname" $ }}-{{ $serviceName }}
  namespace: {{ include "tembo-ai.namespace" $ }}
  labels:
    {{- include "tembo-ai.inferenceService.labels" . | nindent 4 }}
spec:
  clusterIP: None
  type: {{ $mergedConfig.service.type | default "ClusterIP" }}
  ports:
    - port: {{ $mergedConfig.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "tembo-ai.inferenceService.selectorLabels" $ | nindent 4 }}
    app.kubernetes.io/component: {{ $serviceName }}
{{- end }}
{{- end }}
{{- end }}
