apiVersion: v1
kind: Service
metadata:
  name: {{ include "tembo-ai.fullname" . }}-inference-service
  labels:
    {{- include "tembo-ai.inferenceService.labels" . | nindent 4 }}
spec:
  type: {{ .Values.inferenceService.service.type }}
  ports:
    - port: {{ .Values.inferenceService.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "tembo-ai.inferenceService.selectorLabels" . | nindent 4 }}
