{{- range $service := .Values.inferenceService }}
  {{- if (default false $service.serviceAccount.enabled) }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "tembo-ai.inferenceService.serviceAccountName" $ }}-{{ $service.name }}
  labels:
    {{- include "tembo-ai.inferenceService.labels" $ | nindent 4 }}
  {{- with $service.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- if (index $.Values.inferenceService 0).serviceAccount.annotations }}
  annotations:
    {{- toYaml (index $.Values.inferenceService 0).serviceAccount.annotations | nindent 4 }}
  {{- end }}
  {{- end }}
{{- end }}
