{{- range $service := .Values.inferenceService }}
  {{- if (default false $service.statefulSet.enabled) }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "tembo-ai.fullname" $ }}-{{ $service.name | default "default-service" }}-inference-service
  labels:
    {{- include "tembo-ai.inferenceService.labels" $ | nindent 4 }}
spec:
  replicas: {{ default (index $.Values.inferenceService 0).replicaCount $service.replicaCount }}
  selector:
    matchLabels:
      {{- include "tembo-ai.inferenceService.selectorLabels" $ | nindent 6 }}
  serviceName: {{ include "tembo-ai.fullname" $ }}-{{ $service.name | default "default-service" }}-inference-service
  template:
    metadata:
      {{- with $service.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "tembo-ai.inferenceService.selectorLabels" $ | nindent 8 }}
    spec:
      {{- with $service.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "tembo-ai.inferenceService.serviceAccountName" $ }}-{{ $service.name | default "default-service" }}
      securityContext:
        {{- toYaml $service.podSecurityContext | nindent 8 }}
      containers:
        - name: inference-service
          securityContext:
            {{- toYaml $service.securityContext | nindent 12 }}
          image: "{{ $service.image.repository }}:{{ $service.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ $service.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ $service.service.port }}
              protocol: TCP
          {{- if and $service.podMonitor.enabled (ne $service.podMonitor.port "http") }}
            - name: {{ $service.podMonitor.portName }}
              containerPort: {{ $service.podMonitor.containerPort }}
              protocol: TCP
          {{- end }}
          {{- if $service.livenessProbe.enabled }}
          livenessProbe:
            httpGet:
              path: {{ $service.livenessProbe.path }}
              port: {{ $service.livenessProbe.port }}
          {{- end }}
          {{- if $service.readinessProbe.enabled }}
          readinessProbe:
            httpGet:
              path: {{ $service.readinessProbe.path }}
              port: {{ $service.readinessProbe.port }}
          {{- end }}
          {{- if $service.startupProbe.enabled }}
          startupProbe:
            httpGet:
              path: {{ $service.startupProbe.path }}
              port: {{ $service.startupProbe.port }}
            failureThreshold: {{ $service.startupProbe.failureThreshold }}
            periodSeconds: {{ $service.startupProbe.periodSeconds }}
          {{- end }}
          resources:
            {{- toYaml $service.resources | nindent 12 }}
          {{- with $service.args }}
          args:
            {{- toYaml . | nindent 10 }}
          {{- end }}
          {{- with $service.command }}
          command:
            {{- toYaml . | nindent 10 }}
          {{- end }}
          {{- with $service.env }}
          env:
            {{- toYaml . | nindent 10 }}
          {{- end }}
          {{- if $service.persistence.enabled }}
          volumeMounts:
            - name: models
              mountPath: {{ $service.persistence.mountPath }}
          {{- end }}
      {{- with $service.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $service.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $service.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
  volumeClaimTemplates:
    {{- if $service.persistence.enabled }}
    - apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: models
        labels:
          {{- include "tembo-ai.inferenceService.labels" $ | nindent 8 }}
      spec:
        accessModes:
          - {{ $service.persistence.accessMode | default (index $.Values.inferenceService 0).persistence.accessMode }}
        resources:
          requests:
            storage: {{ $service.persistence.size | default (index $.Values.inferenceService 0).persistence.size }}
        {{- if $service.persistence.storageClass }}
        storageClassName: {{ $service.persistence.storageClass }}
        {{- end }}
    {{- end }}
{{- end }}
{{- end }}
