{{- if .Values.inferenceService.services }}
{{- $defaults := .Values.inferenceService.defaults }}
{{- range $serviceName, $serviceConfig := .Values.inferenceService.services }}
{{- $mergedConfig := fromYaml (include "tembo-ai.mergeConfigs" (dict "defaults" $defaults "service" $serviceConfig)) }}
{{- if (default false $mergedConfig.enabled) }}
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "tembo-ai.fullname" $ }}-{{ $serviceName }}
  namespace: {{ include "tembo-ai.namespace" $ }}
  labels:
    {{- include "tembo-ai.inferenceService.labels" . | nindent 4 }}
spec:
  replicas: {{ $mergedConfig.replicaCount }}
  selector:
    matchLabels:
      {{- include "tembo-ai.inferenceService.selectorLabels" $ | nindent 6 }}
      app.kubernetes.io/component: {{ $serviceName }}
  serviceName: {{ include "tembo-ai.fullname" $ }}-{{ $serviceName }}-inference-service
  template:
    metadata:
      {{- with $mergedConfig.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "tembo-ai.inferenceService.selectorLabels" $ | nindent 8 }}
        app.kubernetes.io/component: {{ $serviceName }}
    spec:
      {{- with $mergedConfig.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "tembo-ai.inferenceService.serviceAccountName" $ }}-{{ $serviceName }}
      securityContext:
        {{- toYaml $mergedConfig.podSecurityContext | nindent 8 }}
      containers:
        - name: inference-service
          securityContext:
            {{- toYaml $mergedConfig.securityContext | nindent 12 }}
          image: "{{ $mergedConfig.image.repository }}:{{ $mergedConfig.image.tag | default $.Chart.AppVersion }}"
          imagePullPolicy: {{ $mergedConfig.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ $mergedConfig.service.port }}
              protocol: TCP
          {{- if and $mergedConfig.podMonitor.enabled (ne $mergedConfig.podMonitor.port "http") }}
            - name: {{ $mergedConfig.podMonitor.portName }}
              containerPort: {{ $mergedConfig.podMonitor.containerPort }}
              protocol: TCP
          {{- end }}
          {{- if $mergedConfig.livenessProbe.enabled }}
          livenessProbe:
            httpGet:
              path: {{ $mergedConfig.livenessProbe.path }}
              port: {{ $mergedConfig.livenessProbe.port }}
          {{- end }}
          {{- if $mergedConfig.readinessProbe.enabled }}
          readinessProbe:
            httpGet:
              path: {{ $mergedConfig.readinessProbe.path }}
              port: {{ $mergedConfig.readinessProbe.port }}
          {{- end }}
          {{- if $mergedConfig.startupProbe.enabled }}
          startupProbe:
            httpGet:
              path: {{ $mergedConfig.startupProbe.path }}
              port: {{ $mergedConfig.startupProbe.port }}
            failureThreshold: {{ $mergedConfig.startupProbe.failureThreshold }}
            periodSeconds: {{ $mergedConfig.startupProbe.periodSeconds }}
          {{- end }}
          resources:
            {{- toYaml $mergedConfig.resources | nindent 12 }}
          {{- with $mergedConfig.args }}
          args:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with $mergedConfig.command }}
          command:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with $mergedConfig.env }}
          env:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- if $mergedConfig.persistence.enabled }}
          volumeMounts:
            - name: models
              mountPath: {{ $mergedConfig.persistence.mountPath }}
          {{- end }}
      {{- with $mergedConfig.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $mergedConfig.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $mergedConfig.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
  {{- if $mergedConfig.persistence.enabled }}
  volumeClaimTemplates:
    - apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: models
        labels:
          {{- include "tembo-ai.inferenceService.labels" $ | nindent 10 }}
      spec:
        accessModes:
          - {{ $mergedConfig.persistence.accessMode }}
        resources:
          requests:
            storage: {{ $mergedConfig.persistence.size }}
        {{- if $mergedConfig.persistence.storageClass }}
        storageClassName: {{ $mergedConfig.persistence.storageClass }}
        {{- end }}
  {{- end }}
{{- end }}
{{- end }}
{{- end }}
