FROM quay.io/tembo/tembo-local

RUN trunk install pg_timeseries
RUN trunk install pg_cron
RUN trunk install pg_partman
RUN trunk install postgres_fdw

USER root

RUN echo "shared_preload_libraries = 'pg_cron'" >> $PGDATA/postgresql.conf

USER postgres
