[package]
name = "registry-s3"
version = "0.2.0"
license = "MIT OR Apache-2.0"
description = "Interaction between pgtrunk.io and S3 for storing crate files"
edition = "2021"

[lib]
name = "s3"
path = "lib.rs"

[dependencies]
base64 = "=0.13.1"
chrono = "=0.4.23"
sha-1 = "=0.10.1"
hmac = "=0.12.1"
reqwest = { version = "=0.11.14", features = ["blocking"] }