FROM ubuntu:22.04

RUN apt-get update  -y \
    && apt-get install -y git wget vim numactl gcc-12 g++-12 python3 python3-pip \
    && update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-12 10 --slave /usr/bin/g++ g++ /usr/bin/g++-12

RUN pip install --upgrade pip \
    && pip install wheel packaging ninja "setuptools>=49.4.0" numpy

WORKDIR /app

RUN git clone https://github.com/vllm-project/vllm.git \
    && cd vllm \
    && pip install -v -r requirements-cpu.txt --extra-index-url https://download.pytorch.org/whl/cpu \
    && VLLM_TARGET_DEVICE=cpu python3 setup.py install \
    && cd .. \
    && rm -rf vllm

ENTRYPOINT ["python3", "-m", "vllm.entrypoints.openai.api_server"]
