apiVersion: coredb.io/v1alpha1
kind: CoreDB
metadata:
  name: sample-machine-learning
spec:
  image: "quay.io/tembo/ml-cnpg:15.3.0-1-a3e532d"
  trunk_installs:
    - name: pgvector
      version: 0.5.1
    - name: postgresml
      version: 2.7.1
    - name: pg_embedding
      version: 0.1.0
    - name: pg_cron
      version: 1.5.2
    - name: pgmq
      version: 0.31.0
    - name: vectorize
      version: 0.2.0
    - name: pg_later
      version: 0.0.11
  extensions:
    - name: vector
      locations:
        - database: postgres
          enabled: true
          version: 0.5.0
    - name: pgml
      locations:
        - database: postgres
          enabled: true
          version: 2.7.1
    - name: pg_cron
      locations:
        - database: postgres
          enabled: true
          version: 1.5.2
    - name: pgmq
      locations:
        - database: postgres
          enabled: true
          version: 0.31.0
    - name: vectorize
      locations:
        - database: postgres
          enabled: true
          version: 0.2.0
    - name: pg_later
      locations:
        - database: postgres
          enabled: true
          version: 0.0.11
