apiVersion: coredb.io/v1alpha1
kind: CoreDB
metadata:
  name: sample-olap
spec:
  image: "quay.io/tembo/standard-cnpg:15-389a437"
  stop: false
  stack:
    name: OLAP
    postgres_config:
      - name: checkpoint_timeout
        value: "30min"
      - name: pg_stat_statements.track
        value: all
      - name: track_io_timing
        value: 'on'
      - name: cron.host
        value: /controller/run
      - name: shared_preload_libraries
        value: pg_stat_statements,pg_cron
  trunk_installs:
    - name: pg_stat_statements
      version: 1.10.0
    - name: hydra_columnar
      version: 1.1.1
    - name: pg_partman
      version: 4.7.3
    - name: pg_cron
      version: 1.5.2
    - name: postgres_fdw
      version: 1.1.0
    - name: clerk_fdw
      version: 0.2.4
    - name: redis_fdw
      version: 1.0.0
    - name: parquet_s3_fdw
      version: 1.1.0
    - name: pg_tier
      version: 0.0.3
  extensions:
    - name: pg_stat_statements
      locations:
        - database: postgres
          enabled: true
          version: 1.10.0
    - name: columnar
      locations:
        - database: postgres
          enabled: true
          version: '11.1-10'
    - name: pg_partman
      locations:
        - database: postgres
          enabled: true
          version: 4.7.3
    - name: pg_cron
      description: pg_cron
      locations:
        - database: postgres
          enabled: true
          version: 1.5.2
    - name: postgres_fdw
      description: postgres_fdw
      locations:
        - database: postgres
          enabled: true
          version: '1.1'
    - name: clerk_fdw
      description: clerk_fdw
      locations:
        - database: postgres
          enabled: true
          version: 0.2.4
    - name: redis_fdw
      description: redis_fdw
      locations:
        - database: postgres
          enabled: true
          version: 1.0.0
    - name: parquet_s3_fdw
      description: parquet_s3_fdw
      locations:
        - database: postgres
          enabled: true
          version: 1.1.0
    - name: pg_tier
      description: pg_tier
      locations:
        - database: postgres
          enabled: true
          version: 0.0.3
  runtime_config:
    - name: shared_buffers
      value: "256MB"
    - name: max_connections
      value: "100"
    - name: work_mem
      value: "22MB"
    - name: effective_cache_size
      value: "100MB"
