apiVersion: coredb.io/v1alpha1
kind: CoreDB
metadata:
  name: sample-standard
spec:
  image: "quay.io/tembo/standard-cnpg:15-a0a5ab5"
  stop: false
  stack:
    name: Standard
    postgres_config:
      - name: autovacuum_vacuum_cost_limit
        value: "-1"
      - name: autovacuum_vacuum_scale_factor
        value: "0.05"
      - name: autovacuum_vacuum_insert_scale_factor
        value: "0.05"
      - name: autovacuum_analyze_scale_factor
        value: "0.05"
      - name: checkpoint_timeout
        value: "10min"
      - name: track_activity_query_size
        value: "2048"
      - name: wal_compression
        value: 'on'
      - name: track_io_timing
        value: 'on'
      - name: log_min_duration_statement # https://www.postgresql.org/docs/15/runtime-config-logging.html
        value: "1000"
      - name: pg_stat_statements.track
        value: all
      - name: shared_preload_libraries
        value: pg_stat_statements
  trunk_installs:
    - name: pg_stat_statements
      version: 1.10.0
  extensions:
    - name: pg_stat_statements
      locations:
        - database: postgres
          enabled: true
          version: 1.10.0
  runtime_config:
    - name: shared_buffers
      value: "256MB"
    - name: max_connections
      value: "107"
    - name: work_mem
      value: "5MB"
    - name: bgwriter_delay
      value: "200ms"
    - name: effective_cache_size
      value: "716MB"
    - name: maintenance_work_mem
      value: "64MB"
    - name: max_wal_size
      value: "2GB"
