apiVersion: coredb.io/v1alpha1
kind: CoreDB
metadata:
  name: sample-vectordb
spec:
  image: "quay.io/tembo/standard-cnpg:15-a0a5ab5"
  appServices:
    - image: quay.io/tembo/vector-serve:5caa95d
      name: embeddings
      metrics:
        path: /metrics
        port: 3000
      env:
        - name: TMPDIR
          value: /models
        - name: BATCH_SIZE
          value: "1000"
        - name: XDG_CACHE_HOME
          value: /models/.cache
      routing:
        - port: 3000
          ingressPath: /vectordb
          middlewares:
            - map-embeddings
      middlewares:
        - replacePathRegex:
            name: map-embeddings
            config:
              regex: ^\/vectordb\/?
              replacement: /v1/embeddings
      resources:
        requests:
          cpu: 500m
          memory: 1500Mi
        limits:
          cpu: 4000m
          memory: 1500Mi
      probes:
        readiness:
          path: /ready
          port: 3000
          initialDelaySeconds: 10
        liveness:
          path: /alive
          port: 3000
          initialDelaySeconds: 10
      storage:
        volumeMounts:
        - mountPath: /models
          name: hf-data-vol
        volumes:
        - ephemeral:
            volumeClaimTemplate:
              spec:
                accessModes:
                - ReadWriteOnce
                resources:
                  requests:
                    storage: 2Gi
          name: hf-data-vol
  trunk_installs:
    - name: pgmq
      version: 1.2.1
    - name: vectorize
      version: 0.15.0
    - name: pgvector
      version: 0.7.0
    - name: pg_stat_statements
      version: 1.10.0
  extensions:
    - name: vector
      locations:
        - database: postgres
          enabled: true
          version: 0.5.1
    - name: pg_cron
      locations:
      - database: postgres
        enabled: true
        version: 1.5.2
    - name: pgmq
      locations:
      - database: postgres
        enabled: true
        version: 1.1.1
    - name: vectorize
      locations:
      - database: postgres
        enabled: true
        version: 0.4.0
    - name: pg_stat_statements
      locations:
        - database: postgres
          enabled: true
          version: 1.10.0
  runtime_config:
    - name: cron.host
      value: /controller/run
    - name: vectorize.host
      value: /controller/run
    - name: shared_preload_libraries
      value: vectorize,pg_stat_statements,pg_cron
