apiVersion: coredb.io/v1alpha1
kind: CoreDB
metadata:
  name: sample-vectordb
spec:
  image: "quay.io/tembo/standard-cnpg:15.3.0-1-45c2054"
  trunk_installs:
    - name: pgmq
      version: 0.32.3
    - name: vectorize
      version: 0.4.0
    - name: pgvector
      version: 0.5.1
    - name: pg_stat_statements
      version: 1.10.0
  extensions:
    - name: vector
      locations:
        - database: postgres
          enabled: true
          version: 0.5.1
    - name: pg_cron
      locations:
      - database: postgres
        enabled: true
        version: 1.5.2
    - name: pgmq
      locations:
      - database: postgres
        enabled: true
        version: 0.32.3
    - name: vectorize
      locations:
      - database: postgres
        enabled: true
        version: 0.4.0
    - name: pg_stat_statements
      locations:
        - database: postgres
          enabled: true
          version: 1.10.0
  runtime_config:
    - name: cron.host
      value: /controller/run
    - name: vectorize.host
      value: /controller/run
    - name: shared_preload_libraries
      value: vectorize,pg_stat_statements,pg_cron
