name: 'Build package from a PGX extension'
description: 'Build with PGX inside a container, then output an installable package.'
inputs:
  working-directory:
    description: 'The directory in which there is a pgx extension project'
    required: true
  name:
    description: 'Short name for this extension'
    required: true
  trunk_version:
    description: 'The version of trunk to use for the build'
    required: false
    default: "0.0.1-alpha.3"
  output_dir:
    description: 'The path to output the trunk build'
    required: false
    default: "./.trunk"
  rust_toolchain:
    description: 'The rust toolchain channel to use'
    required: false
    default: "stable"
outputs: {}
runs:
  using: "composite"
  steps:
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: ${{ inputs.toolchain }}
  - name: Install trunk
    shell: bash
    run: |
      cargo install --version ${{ inputs.trunk_version }} pg-trunk
  - name: Run the trunk build
    shell: bash
    working-directory: ${{ inputs.working-directory }}
    run: |
      trunk build --path ${{ inputs.working-directory }} --output-path ${{ inputs.output_dir }}
