{
 "title": "Cloud Tracker",
 "description": "This dashboard works with postgres_exporter for prometheus",
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" },
   { "name": "interval", "label": "Interval", "query": "1s,5s,1m,5m,1h,6h,1d" }
  ]
 },
 "panels": [
  {
   "title": "ADUM",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum ((sum by (namespace) (max_over_time(pg_stat_activity_count{}[24h]))) > bool 2)\n",
     "legendFormat": "24 hour"
    },
    {
     "expr": "sum ((sum by (namespace) (max_over_time(pg_stat_activity_count{}[12h]))) > bool 2)",
     "legendFormat": "12 hour"
    },
    {
     "expr": "sum ((sum by (namespace) (max_over_time(pg_stat_activity_count{}[4h]))) > bool 2)",
     "legendFormat": "4 hour"
    },
    {
     "expr": "sum ((sum by (namespace) (max_over_time(pg_stat_activity_count{}[1h]))) > bool 2)",
     "legendFormat": "1 hour"
    }
   ]
  },
  {
   "title": "Idle (< 3 simultaneous sessions)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum ((sum by (namespace) (max_over_time(pg_stat_activity_count{}[24h]))) < bool 3)\n",
     "legendFormat": "24 hour"
    },
    {
     "expr": "sum ((sum by (namespace) (max_over_time(pg_stat_activity_count{}[12h]))) < bool 3)",
     "legendFormat": "12 hour"
    },
    {
     "expr": "sum ((sum by (namespace) (max_over_time(pg_stat_activity_count{}[4h]))) < bool 3)",
     "legendFormat": "4 hour"
    },
    {
     "expr": "sum ((sum by (namespace) (max_over_time(pg_stat_activity_count{}[1h]))) < bool 3)",
     "legendFormat": "1 hour"
    }
   ]
  },
  {
   "title": "Max number of simultaneous sessions in the last 24 hours",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "(sum by (namespace) (max_over_time(pg_stat_activity_count{}[24h])))\n",
     "legendFormat": "{{namespace}}"
    },
    {
     "expr": "(sum by (namespace) (max_over_time(pg_stat_activity_count{}[12h])))\n",
     "legendFormat": "__auto"
    },
    {
     "expr": "(sum by (namespace) (max_over_time(pg_stat_activity_count{}[4h])))\n",
     "legendFormat": "__auto"
    },
    {
     "expr": "(sum by (namespace) (max_over_time(pg_stat_activity_count{}[1h])))\n",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}