{
 "title": "Data plane dashboard",
 "time": { "from": "now-2d", "to": "now" },
 "refresh": "10m",
 "templating": {
  "list": [
   { "name": "event_search", "label": "Event search" }
  ]
 },
 "panels": [
  { "title": "Postgres storage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total allocated persistent block storage",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 11, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by(persistentvolumeclaim) (kubelet_volume_stats_available_bytes{job=\"kubelet\", metrics_path=\"/metrics\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Remaining persistent block storage",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 11, "x": 11, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "1 - sum by(persistentvolumeclaim) (kubelet_volume_stats_available_bytes{job=\"kubelet\", metrics_path=\"/metrics\"}) / sum by(persistentvolumeclaim) (kubelet_volume_stats_capacity_bytes{job=\"kubelet\", metrics_path=\"/metrics\"})",
     "legendFormat": "__auto"
    },
    { "expr": "1", "legendFormat": "limit" }
   ]
  },
  { "title": "Queues", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "Number Messages in Queue",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "pgmq_queue_length{job=~\"org-coredb-inst-cp-queue-.*-metrics\"}",
     "legendFormat": "{{queue_name}}"
    }
   ]
  },
  {
   "title": "Num Messages per Minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "targets": [
    {
     "expr": "pgmq_total_messages{job=~\"org-coredb-inst-cp-queue-.*-metrics\"} -  pgmq_total_messages{job=~\"org-coredb-inst-cp-queue-.*-metrics\"} offset 1m",
     "legendFormat": "{{queue_name}}"
    }
   ]
  },
  {
   "title": "Num Messages past 24hr",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
   "targets": [
    {
     "expr": "pgmq_total_messages{job=~\"org-coredb-inst-cp-queue-.*-metrics\"} -  pgmq_total_messages{job=~\"org-coredb-inst-cp-queue-.*-metrics\"} offset 24h",
     "legendFormat": "{{queue_name}}"
    }
   ]
  },
  {
   "title": "Total Messages Created",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
   "targets": [
    {
     "expr": "pgmq_total_messages{job=~\"org-coredb-inst-cp-queue-.*-metrics\"}",
     "legendFormat": "{{queue_name}}"
    }
   ]
  },
  {
   "title": "Oldest Message Age (minutes)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pgmq_oldest_msg_age_sec{job=~\"org-coredb-inst-cp-queue-.*-metrics\"} / 60",
     "legendFormat": "{{queue_name}}"
    }
   ]
  },
  {
   "title": "Youngest Message Age (minutes)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 31 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pgmq_newest_msg_age_sec{job=~\"org-coredb-inst-cp-queue-.*-metrics\"} / 60",
     "legendFormat": "{{queue_name}}"
    }
   ]
  },
  {
   "title": "Node replacement troubleshooting",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 }
  },
  {
   "title": "Postgres or Grafana containers not running",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "(kube_pod_container_status_running{container=~\"postgres|grafana\"} < 1) + 1",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Events",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "targets": [
    {
     "expr": "{namespace=\"monitoring\", app=\"k8s-event-logger\"} |= `$event_search` | json"
    }
   ]
  },
  {
   "title": "Spot interruptions",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
   "targets": [
    {
     "expr": "{namespace=\"monitoring\", app=\"k8s-event-logger\"} |= `InstanceSpotInterrupted` | json"
    }
   ]
  },
  {
   "title": "Pods not running or succeeded",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 49 },
   "targets": [
    {
     "expr": "kube_pod_status_phase{phase!~\"Running|Succeeded\"} > 0",
     "legendFormat": "{{phase}} : {{pod}}"
    }
   ]
  },
  {
   "title": "Spot interruptions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 56 },
   "targets": [
    {
     "expr": "count_over_time({namespace=\"monitoring\", app=\"k8s-event-logger\"} |= `InstanceSpotInterrupted` [$__interval])",
     "legendFormat": "interrupts"
    }
   ]
  },
  {
   "title": "Hours running per node",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 58 },
   "targets": [
    {
     "expr": "(time() - kube_node_created{node!~\"fargate-.*\"}) / 3600",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "New nodes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 64 },
   "targets": [
    {
     "expr": "(((time() - kube_node_created{node!~\"fargate-.*\"}) / 3600) < bool 4) > 0",
     "legendFormat": "{{node}}"
    }
   ]
  }
 ]
}