{
 "title": "Control Plane Queues",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Number Messages in Queue",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "pgmq_queue_length{job=~\"org-coredb-inst-cp-queue-.*-metrics\"}",
     "legendFormat": "{{queue_name}}"
    }
   ]
  },
  {
   "title": "Num Messages Archived past 24hr",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "pgmq_num_archived{job=~\"org-coredb-inst-cp-queue-.*-metrics\"} -  pgmq_num_archived{job=~\"org-coredb-inst-cp-queue-.*-metrics\"} offset 24h",
     "legendFormat": "{{queue_name}}"
    }
   ]
  },
  {
   "title": "Num Messages Archived per Minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "pgmq_num_archived{job=~\"org-coredb-inst-cp-queue-.*-metrics\"} -  pgmq_num_archived{job=~\"org-coredb-inst-cp-queue-.*-metrics\"} offset 1m",
     "legendFormat": "{{queue_name}}"
    }
   ]
  },
  {
   "title": "Total Archived Messages",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "pgmq_num_archived{job=~\"org-coredb-inst-cp-queue-.*-metrics\"}",
     "legendFormat": "{{queue_name}}"
    }
   ]
  },
  {
   "title": "Oldest Message Age (minutes)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pgmq_oldest_msg_age_sec{job=~\"org-coredb-inst-cp-queue-.*-metrics\"} / 60",
     "legendFormat": "{{queue_name}}"
    }
   ]
  },
  {
   "title": "Youngest Message Age (minutes)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pgmq_newest_msg_age_sec{job=~\"org-coredb-inst-cp-queue-.*-metrics\"} / 60",
     "legendFormat": "{{queue_name}}"
    }
   ]
  }
 ]
}