{
 "title": "Who is using tembo cloud?",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "mem_billing", "label": "$ / 1 Gi / mo", "query": "4.05" },
   { "name": "cpu_billing", "label": "$ / CPU / mo", "query": "53.96" },
   { "name": "percent_billed", "label": "percent billed", "query": "100" }
  ]
 },
 "panels": [
  {
   "title": "Hypothetical monthly revenue per org, top 100",
   "type": "barchart",
   "gridPos": { "h": 16, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "expr": "topk(100,(\n  $percent_billed * $cpu_billing * (\n    sum(\n      kube_pod_container_resource_limits{container=\"postgres\", resource=\"cpu\"} \n      * on(namespace) group_left(label_tembo_io_organization_id)\n      kube_namespace_labels{label_tembo_io_organization_id!=\"\"}\n    ) by (label_tembo_io_organization_id)\n  ) / 100\n)\n+\n(\n  $percent_billed * (\n    sum(\n      $mem_billing * kube_pod_container_resource_limits{container=\"postgres\", resource=\"memory\"} / 1073741824\n      * on(namespace) group_left(label_tembo_io_organization_id)\n      kube_namespace_labels{label_tembo_io_organization_id!=\"\"}\n    ) by (label_tembo_io_organization_id)\n  ) / 100\n))\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total transactions, past week, per org, top 100",
   "type": "barchart",
   "gridPos": { "h": 16, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "million" } },
   "targets": [
    {
     "expr": "topk(100,sum by (label_tembo_io_organization_id) (\n  sum by (namespace) (increase(pg_stat_database_xact_commit{}[1w]))\n  * on(namespace) group_left(label_tembo_io_organization_id)\n  kube_namespace_labels{label_tembo_io_organization_id!=\"\"}\n)) / 1000000\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Peak TPS in the last week, per org",
   "type": "barchart",
   "gridPos": { "h": 16, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "TPS" } },
   "targets": [
    {
     "expr": "topk(100, sum by (label_tembo_io_organization_id) (\n  sum by (namespace) (max_over_time(rate(pg_stat_database_xact_commit{}[5m])[1d:5m]))\n  * on(namespace) group_left(label_tembo_io_organization_id)\n  kube_namespace_labels{label_tembo_io_organization_id!=\"\"}\n))\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total postgres servers",
   "type": "barchart",
   "description": "includes replicas",
   "gridPos": { "h": 16, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "topk(100,sum by (label_tembo_io_organization_id) (\n  count by (namespace) (kube_pod_container_info{container=\"postgres\"})\n  * on(namespace) group_left(label_tembo_io_organization_id)\n  kube_namespace_labels{label_tembo_io_organization_id!=\"\"}\n))\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total storage used, per org, top 100",
   "type": "barchart",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "topk(100,sum by (label_tembo_io_organization_id) (\n  sum by (namespace) (kubelet_volume_stats_used_bytes)\n  * on(namespace) group_left(label_tembo_io_organization_id) \n  kube_namespace_labels{label_tembo_io_organization_id!=\"\"}\n))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Transactions per second, by org",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "TPS" } },
   "targets": [
    {
     "expr": "sum by (label_tembo_io_organization_id) (\n  sum by (namespace) (rate(pg_stat_database_xact_commit{}[1m]))\n  * on(namespace) group_left(label_tembo_io_organization_id)\n  kube_namespace_labels{label_tembo_io_organization_id!=\"\"}\n)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total storage used, per org, over time",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (label_tembo_io_organization_id) (\n  sum by (namespace) (kubelet_volume_stats_used_bytes)\n  * on(namespace) group_left(label_tembo_io_organization_id) \n  kube_namespace_labels{label_tembo_io_organization_id!=\"\"}\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Hypothetical monthly bill over time",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 70 },
   "targets": [
    {
     "expr": "(\n  $percent_billed * $cpu_billing * (\n    sum(\n      kube_pod_container_resource_limits{container=\"postgres\", resource=\"cpu\"} \n      * on(namespace) group_left(label_tembo_io_organization_id)\n      kube_namespace_labels{label_tembo_io_organization_id!=\"\"}\n    ) by (label_tembo_io_organization_id)\n  ) / 100\n)\n+\n(\n  $percent_billed * (\n    sum(\n      $mem_billing * kube_pod_container_resource_limits{container=\"postgres\", resource=\"memory\"} / 1073741824\n      * on(namespace) group_left(label_tembo_io_organization_id)\n      kube_namespace_labels{label_tembo_io_organization_id!=\"\"}\n    ) by (label_tembo_io_organization_id)\n  ) / 100\n)\n",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}