[package]
name = "pgmq"
version = "0.0.1"
edition = "2021"

description = "A Rust client for Postgres Message Queues"
documentation = "https://github.com/CoreDB-io/coredb/crates/pgmq"
homepage = "https://www.coredb.io"
keywords = ["messaging", "queues", "postgres"]
license = "MIT"
readme = "README.md"
repo = "https://github.com/CoreDB-io/coredb/crates/pgmq"

[dependencies]
chrono = "0.4.23"
serde_json = "1.0.91"
sqlx = { version = "0.6", features = [ "runtime-tokio-native-tls" , "postgres", "chrono" ] }
tokio = { version = "1", features = ["full"] }
