name: 'Generate and Deploy Documentation'
description: 'Generate and deploy documentation files.'
inputs:
  repository:
    description: 'GitHub repository to work with.'
    required: true
  ssh_key:
    description: 'SSH key for the repository access.'
    required: true
  branch:
    description: 'Branch to checkout and update.'
    required: true
  repo_into:
    description: 'repo to checkout and update.'
    required: true

on:
  push:
    paths:
      - 'tembo-cli/**'
    branches:
      - main
  pull_request:
    paths:
      - 'tembo-cli/**'
    branches:
      - main
      - develop
      - feature/*

runs:
  using: "composite"
  steps:
    - name: Check out the repo
      uses: actions/checkout@v4
      with:
        repository: ${{ inputs.repository }}
        ssh-key: ${{ inputs.ssh_key }}
        ref: ${{ inputs.branch }}
        repo-into: ${{ inputs.repo_into }}

    - name: List directory contents
      run: ls -lah
      shell: bash

    - name: Change to tembo-cli directory
      run: |
        if [ -d "tembo-cli" ]; then
          cd tembo-cli
          cargo run -- --markdown-help > command-reference.md
        else
          echo "Directory tembo-cli not found!"
          exit 1
        fi
      shell: bash

      - name: Check out the repo
        uses: actions/checkout@v4
        with:
          repository: ${{ inputs.repo_into }}
          ssh-key: ${{ inputs.ssh_key }}
          ref: ${{ inputs.branch }}

      - name: Copy documentation to website repository
        run: |
          cp tembo-cli/command-reference.md website-repo/src/content/docs/development/cli
        shell: bash

      - name: Push Documentation to Website Repository
        run: |
          set -xe
          git config --global user.name "coredb-service-user"
          git config --global user.email "admin@github.com"
          git fetch https://github.com/tembo-io/website.git
          cd src/content/docs/development/cli
          git add src/content/docs/development/cli/command-reference.md
          git checkout ${{ inputs.branch }} || git checkout -b ${{ inputs.branch }}
          git commit -m "Update command reference documentation"
          git push origin ${{ inputs.branch }}
        shell: bash
