name: 'Generate and Deploy Documentation'
description: 'Generate and deploy documentation files.'
inputs:
  repository:
    description: 'GitHub repository to work with.'
    required: true
  ssh_key:
    description: 'SSH key for the repository access.'
    required: true
  branch:
    description: 'Branch to checkout and update.'
    required: true
on:
  push:
    paths:
      - 'tembo-cli/**'
    branches:
      - main
  pull_request:
    paths:
      - 'tembo-cli/**'
    branches:
      - main
      - develop
      - feature/*

runs:
  using: "composite"
  steps:
    - name: Check out the repo
      uses: actions/checkout@v4
      with:
        repository: ${{ inputs.repository }}
        ssh-key: ${{ inputs.ssh_key }}
    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true

    - name: Generate Documentation
      run: |
        cd tembo-cli
        cargo run -- --markdown-help > command-reference.md

    - name: Push Documentation to Website Repository
      run: |
        set -xe
        cd ${{ inputs.repository }}
        git config --global user.name "coredb-service-user"
        git config --global user.email "admin+github@coredb.io"
        git fetch
        git checkout ${{ inputs.branch }} || git checkout -b ${{ inputs.branch }}
        mkdir -p src/content/docs/development/cli
        cp command-reference.md src/content/docs/development/cli
        git add src/content/docs/development/cli/command-reference.md
        git commit -m "Update command reference documentation"
        git push origin ${{ inputs.branch }}
