[instance-1]
environment = "dev"
instance_name = "instance-1"
cpu = "1"
storage = "50Gi"
replicas = 1
stack_type = "Standard"

[instance-2]
environment = "dev"
instance_name = "instance-2"
cpu = "1"
storage = "50Gi"
replicas = 1
stack_type = "OLTP"

[[instance-2.app_services]]
restapi = { }
