# Binding the role to the account in coredb-operator ns
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: coredb-controller-binding
subjects:
  - kind: ServiceAccount
    namespace: coredb-operator
    name: coredb-controller
roleRef:
  kind: ClusterRole
  name: control-cdb
  apiGroup: rbac.authorization.k8s.io
