# Main deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: coredb-controller
  namespace: coredb-operator
  labels:
    app: coredb-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: coredb-controller
  template:
    metadata:
      labels:
        app: coredb-controller
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
    spec:
      serviceAccountName: coredb-controller
      containers:
      - name: coredb-controller
        image: quay.io/coredb/coredb-operator:latest
        imagePullPolicy: Always
        resources:
          limits:
            cpu: 200m
            memory: 256Mi
          requests:
            cpu: 50m
            memory: 100Mi
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP
        env:
        # We are pointing to tempo or grafana tracing agent's otlp grpc receiver port
        - name: OPENTELEMETRY_ENDPOINT_URL
          value: "https://10.96.239.210:8080"
        - name: RUST_LOG
          value: "info,kube=debug,controller=debug"
        readinessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 5
          periodSeconds: 5
