# Expose the http port of the service
apiVersion: v1
kind: Service
metadata:
  name: coredb-controller
  namespace: coredb-operator
  labels:
    app: coredb-controller
spec:
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app: coredb-controller
