apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "tembo-ai.fullname" . }}-gateway
  labels:
    {{- include "tembo-ai.inferenceGateway.labels" . | nindent 4 }}
spec:
  {{- if not .Values.inferenceGateway.autoscaling.enabled }}
  replicas: {{ .Values.inferenceGateway.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "tembo-ai.inferenceGateway.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.inferenceGateway.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "tembo-ai.inferenceGateway.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.inferenceGateway.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "tembo-ai.inferenceGateway.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.inferenceGateway.podSecurityContext | nindent 8 }}
      containers:
        - name: inference-gateway
          securityContext:
            {{- toYaml .Values.inferenceGateway.securityContext | nindent 12 }}
          image: "{{ .Values.inferenceGateway.image.repository }}:{{ .Values.inferenceGateway.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.inferenceGateway.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.inferenceGateway.service.port }}
              protocol: TCP
          {{- if and .Values.inferenceGateway.podMonitor.enabled (ne .Values.inferenceGateway.podMonitor.port "http") }}
            - name: {{ .Values.inferenceGateway.podMonitor.portName }}
              containerPort: {{ .Values.inferenceGateway.podMonitor.containerPort }}
              protocol: TCP
          {{- end }}
          {{- if .Values.inferenceGateway.livenessProbe.enabled }}
          livenessProbe:
            httpGet:
              path: {{ .Values.inferenceGateway.livenessProbe.path }}
              port: {{ .Values.inferenceGateway.livenessProbe.port }}
          {{- end }}
          {{- if .Values.inferenceGateway.readinessProbe.enabled }}
          readinessProbe:
            httpGet:
              path: {{ .Values.inferenceGateway.readinessProbe.path }}
              port: {{ .Values.inferenceGateway.readinessProbe.port }}
          {{- end }}
          resources:
            {{- toYaml .Values.inferenceGateway.resources | nindent 12 }}
          {{- with .Values.inferenceGateway.args }}
          args:
            {{- toYaml . | nindent 10 }}
          {{- end }}
          {{- with .Values.inferenceGateway.command }}
          command:
            {{- toYaml . | nindent 10 }}
          {{- end }}
          {{- with .Values.inferenceGateway.env }}
          env:
            {{- toYaml . | nindent 10 }}
          {{- end }}
      {{- with .Values.inferenceGateway.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.inferenceGateway.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.inferenceGateway.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
