{{- if .Values.inferenceGateway.externalSecrets.secretName -}}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "tembo-ai.fullname" . }}-inference-gateway
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "tembo-ai.inferenceGateway.labels" . | nindent 4 }}
spec:
  refreshInterval: {{ .Values.inferenceGateway.externalSecrets.refreshInterval }}
  secretStoreRef:
    name: {{ .Values.inferenceGateway.externalSecrets.parameterStore.name }}
    kind: {{ .Values.inferenceGateway.externalSecrets.parameterStore.kind }}
  target:
    creationPolicy: 'Owner'
    name: {{ .Values.inferenceGateway.externalSecrets.secretName }}
  dataFrom:
  - find:
      name:
        regexp: {{ .Values.inferenceGateway.externalSecrets.secretRegex }}
{{- end }}
