{{- if .Values.inferenceGateway.autoscaling.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "tembo-ai.fullname" . }}-gateway
  labels:
    {{- include "tembo-ai.inferenceGateway.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "tembo-ai.fullname" . }}-gateway
  minReplicas: {{ .Values.inferenceGateway.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.inferenceGateway.autoscaling.maxReplicas }}
  metrics:
    {{- if .Values.inferenceGateway.autoscaling.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        targetAverageUtilization: {{ .Values.inferenceGateway.autoscaling.targetCPUUtilizationPercentage }}
    {{- end }}
{{- end }}
