{{- if .Values.inferenceGateway.ingressRoute.enabled -}}
{{- $fullName := include "tembo-ai.fullname" . -}}
{{- $svcPort := .Values.inferenceGateway.service.port -}}
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: {{ $fullName }}-gateway
  labels:
    {{- include "tembo-ai.inferenceGateway.labels" . | nindent 4 }}
spec:
  entryPoints:
    - websecure
  routes:
    - match: {{ .Values.inferenceGateway.ingressRoute.match }}
      kind: Rule
      services:
        - name: {{ $fullName }}-gateway
          port: {{ $svcPort }}
  tls: {}
{{- end }}
