{{- if .Values.inferenceGateway.internalLoadBalancer.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "tembo-ai.fullname" . }}-gateway-internal-lb
  labels:
    {{- include "tembo-ai.inferenceGateway.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.inferenceGateway.internalLoadBalancer.annotations | nindent 4 }}
    {{- if .Values.inferenceGateway.internalLoadBalancer.route53.enabled }}
    external-dns.alpha.kubernetes.io/hostname: {{ .Values.inferenceGateway.internalLoadBalancer.route53.recordName }}.{{ .Values.inferenceGateway.internalLoadBalancer.route53.zoneName }}
    external-dns.alpha.kubernetes.io/ttl: {{ .Values.inferenceGateway.internalLoadBalancer.route53.ttl | quote }}
    {{- end }}

spec:
  type: LoadBalancer
  ports:
    - port: {{ .Values.inferenceGateway.internalLoadBalancer.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "tembo-ai.inferenceGateway.selectorLabels" . | nindent 4 }}
{{- end }}
