apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "tembo-ai.inferenceGateway.serviceAccountName" . }}
  labels:
    {{- include "tembo-ai.inferenceGateway.labels" . | nindent 4 }}
  {{- with .Values.inferenceGateway.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
