{{- if .Values.inferenceGateway.internalLoadBalancer.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "tembo-ai.fullname" . }}-gateway-internal-lb
  labels:
    {{- include "tembo-ai.inferenceGateway.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.inferenceGateway.internalLoadBalancer.annotations | nindent 4 }}
spec:
  type: LoadBalancer
  ports:
    - port: {{ .Values.inferenceGateway.internalLoadBalancer.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "tembo-ai.inferenceGateway.selectorLabels" . | nindent 4 }}
{{- end }}
