FROM quay.io/tembo/tembo-local:latest

# Optional:
# Install any extensions you want with Trunk
{% for key, value in extensions %}
{% if value.trunk_project and value.trunk_project_version %}
RUN trunk install --version {{value.trunk_project_version}} {{value.trunk_project}}
{% elif value.trunk_project %}
RUN trunk install {{value.trunk_project}}
{% endif %}
{% endfor %}

# Optional:
# Specify extra Postgres configurations by copying into this directory
COPY postgres.conf $PGDATA/extra-configs