FROM quay.io/tembo/tembo-local:latest

{% for trunk_install in trunk_installs %}
{% if trunk_install.version %}
RUN trunk install --version {{trunk_install.version}} {{trunk_install.name}}
{% else %}
RUN trunk install {{trunk_install.name}}
{% endif %}
{% endfor %}

# Optional:
# Specify extra Postgres configurations by copying into this directory
COPY postgres.conf $PGDATA/extra-configs