apiVersion: coredb.io/v1alpha1
kind: CoreDB
metadata:
  name: sample-coredb
spec:
  stop: false
  extensions:
    - name: pg_stat_statements
      locations: 
        - enabled: true
          database: postgres
          schema: public
          version: "1.9"
