pub mod backups;
pub mod clusters;
pub(crate) mod cnpg;
// pub(crate) mod cnpg_backups;
pub(crate) mod archive;
pub mod cnpg_utils;
pub mod hibernate;
pub(crate) mod placement;
pub mod poolers;
pub mod retention;
mod scheduledbackups;
pub const VOLUME_SNAPSHOT_CLASS_NAME: &str = "cnpg-snapshot-class";
