/*
 * Tembo Cloud
 *
 * Platform API for Tembo Cloud             </br>             </br>             To find a Tembo Data API, please find it here:             </br>             </br>             [AWS US East 1](https://api.data-1.use1.tembo.io/swagger-ui/)
 *
 * The version of the OpenAPI document: v1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct AppType {
    #[serde(rename = "restapi", deserialize_with = "Option::deserialize")]
    pub restapi: Option<Box<crate::models::AppConfig>>,
    #[serde(rename = "http", deserialize_with = "Option::deserialize")]
    pub http: Option<Box<crate::models::AppConfig>>,
    #[serde(rename = "custom")]
    pub custom: Box<crate::models::AppService>,
}

impl AppType {
    pub fn new(
        restapi: Option<crate::models::AppConfig>,
        http: Option<crate::models::AppConfig>,
        custom: crate::models::AppService,
    ) -> AppType {
        AppType {
            restapi: if let Some(x) = restapi {
                Some(Box::new(x))
            } else {
                None
            },
            http: if let Some(x) = http {
                Some(Box::new(x))
            } else {
                None
            },
            custom: Box::new(custom),
        }
    }
}
