/*
 * Tembo Cloud
 *
 * Platform API for Tembo Cloud             </br>             </br>             To find a Tembo Data API, please find it here:             </br>             </br>             [AWS US East 1](https://api.data-1.use1.tembo.io/swagger-ui/)
 *
 * The version of the OpenAPI document: v1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ConnectionPooler {
    #[serde(rename = "enabled", skip_serializing_if = "Option::is_none")]
    pub enabled: Option<bool>,
    #[serde(rename = "pooler", skip_serializing_if = "Option::is_none")]
    pub pooler: Option<Box<crate::models::PgBouncer>>,
}

impl ConnectionPooler {
    pub fn new() -> ConnectionPooler {
        ConnectionPooler {
            enabled: None,
            pooler: None,
        }
    }
}
