/*
 * Tembo Cloud
 *
 * Platform API for Tembo Cloud             </br>             </br>             To find a Tembo Data API, please find it here:             </br>             </br>             [AWS US East 1](https://api.data-1.use1.tembo.io/swagger-ui/)             
 *
 * The version of the OpenAPI document: v1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */


/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Environment {
    #[serde(rename = "dev")]
    Dev,
    #[serde(rename = "test")]
    Test,
    #[serde(rename = "prod")]
    Prod,

}

impl ToString for Environment {
    fn to_string(&self) -> String {
        match self {
            Self::Dev => String::from("dev"),
            Self::Test => String::from("test"),
            Self::Prod => String::from("prod"),
        }
    }
}

impl Default for Environment {
    fn default() -> Environment {
        Self::Dev
    }
}




