/*
 * Tembo Cloud
 *
 * Platform API for Tembo Cloud             </br>             </br>             To find a Tembo Data API, please find it here:             </br>             </br>             [AWS US East 1](https://api.data-1.use1.tembo.io/swagger-ui/)
 *
 * The version of the OpenAPI document: v1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct Extension {
    #[serde(
        rename = "description",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub description: Option<Option<String>>,
    #[serde(rename = "locations")]
    pub locations: Vec<crate::models::ExtensionInstallLocation>,
    #[serde(rename = "name")]
    pub name: String,
}

impl Extension {
    pub fn new(locations: Vec<crate::models::ExtensionInstallLocation>, name: String) -> Extension {
        Extension {
            description: None,
            locations,
            name,
        }
    }
}
