/*
 * Tembo Cloud
 *
 * Platform API for Tembo Cloud             </br>             </br>             To find a Tembo Data API, please find it here:             </br>             </br>             [AWS US East 1](https://api.data-1.use1.tembo.io/swagger-ui/)
 *
 * The version of the OpenAPI document: v1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

/// Middleware : Midddleware is used to configure the middleware for the appService. This is specifically configured for the ingress controller Traefik.  Please refer to the example in the `AppService` documentation.

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct Middleware {
    #[serde(rename = "customRequestHeaders")]
    pub custom_request_headers: Box<crate::models::HeaderConfig>,
    #[serde(rename = "stripPrefix")]
    pub strip_prefix: Box<crate::models::StripPrefixConfig>,
    #[serde(rename = "replacePathRegex")]
    pub replace_path_regex: Box<crate::models::ReplacePathRegexConfig>,
}

impl Middleware {
    /// Midddleware is used to configure the middleware for the appService. This is specifically configured for the ingress controller Traefik.  Please refer to the example in the `AppService` documentation.
    pub fn new(
        custom_request_headers: crate::models::HeaderConfig,
        strip_prefix: crate::models::StripPrefixConfig,
        replace_path_regex: crate::models::ReplacePathRegexConfig,
    ) -> Middleware {
        Middleware {
            custom_request_headers: Box::new(custom_request_headers),
            strip_prefix: Box::new(strip_prefix),
            replace_path_regex: Box::new(replace_path_regex),
        }
    }
}
