/*
 * Tembo Cloud
 *
 * Platform API for Tembo Cloud             </br>             </br>             To find a Tembo Data API, please find it here:             </br>             </br>             [AWS US East 1](https://api.data-1.use1.tembo.io/swagger-ui/)             
 *
 * The version of the OpenAPI document: v1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct Probes {
    #[serde(rename = "liveness")]
    pub liveness: Box<crate::models::Probe>,
    #[serde(rename = "readiness")]
    pub readiness: Box<crate::models::Probe>,
}

impl Probes {
    pub fn new(liveness: crate::models::Probe, readiness: crate::models::Probe) -> Probes {
        Probes {
            liveness: Box::new(liveness),
            readiness: Box::new(readiness),
        }
    }
}


