/*
 * Tembo Cloud
 *
 * Platform API for Tembo Cloud             </br>             </br>             To find a Tembo Data API, please find it here:             </br>             </br>             [AWS US East 1](https://api.data-1.use1.tembo.io/swagger-ui/)
 *
 * The version of the OpenAPI document: v1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ReplacePathRegexConfig {
    #[serde(rename = "config")]
    pub config: Box<crate::models::ReplacePathRegexConfigType>,
    #[serde(rename = "name")]
    pub name: String,
}

impl ReplacePathRegexConfig {
    pub fn new(
        config: crate::models::ReplacePathRegexConfigType,
        name: String,
    ) -> ReplacePathRegexConfig {
        ReplacePathRegexConfig {
            config: Box::new(config),
            name,
        }
    }
}
