/*
 * Tembo Cloud
 *
 * Platform API for Tembo Cloud             </br>             </br>             To find a Tembo Data API, please find it here:             </br>             </br>             [AWS US East 1](https://api.data-1.use1.tembo.io/swagger-ui/)             
 *
 * The version of the OpenAPI document: v1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct Routing {
    #[serde(rename = "entryPoints", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub entry_points: Option<Option<Vec<String>>>,
    #[serde(rename = "ingressPath", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub ingress_path: Option<Option<String>>,
    #[serde(rename = "ingressType", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub ingress_type: Option<Option<crate::models::IngressType>>,
    #[serde(rename = "middlewares", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub middlewares: Option<Option<Vec<String>>>,
    #[serde(rename = "port")]
    pub port: i32,
}

impl Routing {
    pub fn new(port: i32) -> Routing {
        Routing {
            entry_points: None,
            ingress_path: None,
            ingress_type: None,
            middlewares: None,
            port,
        }
    }
}


