/*
 * Tembo Cloud
 *
 * Platform API for Tembo Cloud             </br>             </br>             To find a Tembo Data API, please find it here:             </br>             </br>             [AWS US East 1](https://api.data-1.use1.tembo.io/swagger-ui/)             
 *
 * The version of the OpenAPI document: v1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */


/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum StackType {
    #[serde(rename = "Standard")]
    Standard,
    #[serde(rename = "MessageQueue")]
    MessageQueue,
    #[serde(rename = "MachineLearning")]
    MachineLearning,
    #[serde(rename = "OLAP")]
    Olap,
    #[serde(rename = "OLTP")]
    Oltp,
    #[serde(rename = "VectorDB")]
    VectorDb,
    #[serde(rename = "DataWarehouse")]
    DataWarehouse,

}

impl Default for StackType {
    fn default() -> StackType {
        Self::Standard
    }
}




