/*
 * Tembo Cloud
 *
 * Platform API for Tembo Cloud             </br>             </br>             To find a Tembo Data API, please find it here:             </br>             </br>             [AWS US East 1](https://api.data-1.use1.tembo.io/swagger-ui/)
 *
 * The version of the OpenAPI document: v1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum State {
    #[serde(rename = "Submitted")]
    Submitted,
    #[serde(rename = "Up")]
    Up,
    #[serde(rename = "Configuring")]
    Configuring,
    #[serde(rename = "Error")]
    Error,
    #[serde(rename = "Restarting")]
    Restarting,
    #[serde(rename = "Starting")]
    Starting,
    #[serde(rename = "Stopping")]
    Stopping,
    #[serde(rename = "Stopped")]
    Stopped,
    #[serde(rename = "Deleting")]
    Deleting,
    #[serde(rename = "Deleted")]
    Deleted,
}

impl ToString for State {
    fn to_string(&self) -> String {
        match self {
            Self::Submitted => String::from("Submitted"),
            Self::Up => String::from("Up"),
            Self::Configuring => String::from("Configuring"),
            Self::Error => String::from("Error"),
            Self::Restarting => String::from("Restarting"),
            Self::Starting => String::from("Starting"),
            Self::Stopping => String::from("Stopping"),
            Self::Stopped => String::from("Stopped"),
            Self::Deleting => String::from("Deleting"),
            Self::Deleted => String::from("Deleted"),
        }
    }
}

impl Default for State {
    fn default() -> State {
        Self::Submitted
    }
}
