kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "conductor.fullname" . }}
subjects:
- kind: ServiceAccount
  namespace: {{ .Release.Namespace }}
  name: {{ include "conductor.serviceAccountName" . }}
roleRef:
  kind: ClusterRole
  name: {{ include "conductor.fullname" . }}
  apiGroup: rbac.authorization.k8s.io
