apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "conductor.fullname" . }}-watcher
  labels:
    {{- include "conductor.watcherLabels" . | nindent 4 }}
spec:
  replicas: {{ include "conductor.replicaCount" (list "watcher" .) }}
  selector:
    matchLabels:
      {{- include "conductor.watcherSelectorLabels" . | nindent 6 }}
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "conductor.watcherSelectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "conductor.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          command:
          - ./usr/local/bin/conductor
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          env:
          - name: CONDUCTOR_ENABLED
            value: "false"
          - name: WATCHER_ENABLED
            value: "true"
          - name: RUST_LOG
            value: {{ .Values.logLevel }}
          {{- if .Values.env }}{{ .Values.env | default list | toYaml | nindent 10 }}{{- end }}
          {{- with (index .Values ).extraEnv }}
          {{- range . }}
          - name: {{ .name }}
            value: {{ tpl (.value | quote) $ }}
          {{- end }}
          {{- end }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          livenessProbe:
            httpGet:
              path: "/health/lively"
              port: http
          readinessProbe:
            httpGet:
              path: "/health/lively"
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
