/*
 * Tembo Cloud
 *
 * Platform API for Tembo Cloud             </br>             </br>             To find a Tembo Data API, please find it here:             </br>             </br>             [AWS US East 1](https://api.data-1.use1.tembo.io/swagger-ui/)
 *
 * The version of the OpenAPI document: v1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AppTypeOneOf6 {
    #[serde(rename = "custom")]
    pub custom: Box<models::AppService>,
}

impl AppTypeOneOf6 {
    pub fn new(custom: models::AppService) -> AppTypeOneOf6 {
        AppTypeOneOf6 {
            custom: Box::new(custom),
        }
    }
}
