/*
 * Tembo Cloud
 *
 * Platform API for Tembo Cloud             </br>             </br>             To find a Tembo Data API, please find it here:             </br>             </br>             [AWS US East 1](https://api.data-1.use1.tembo.io/swagger-ui/)
 *
 * The version of the OpenAPI document: v1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AppTypeOneOf {
    #[serde(rename = "restapi", deserialize_with = "Option::deserialize")]
    pub restapi: Option<Box<models::AppConfig>>,
}

impl AppTypeOneOf {
    pub fn new(restapi: Option<models::AppConfig>) -> AppTypeOneOf {
        AppTypeOneOf {
            restapi: if let Some(x) = restapi {
                Some(Box::new(x))
            } else {
                None
            },
        }
    }
}
