/*
 * Tembo Cloud
 *
 * Platform API for Tembo Cloud             </br>             </br>             To find a Tembo Data API, please find it here:             </br>             </br>             [AWS US East 1](https://api.data-1.use1.tembo.io/swagger-ui/)
 *
 * The version of the OpenAPI document: v1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AppMetrics {
    /// path to scrape metrics
    #[serde(rename = "path")]
    pub path: String,
    /// port must be also exposed in one of AppService.routing[]
    #[serde(rename = "port")]
    pub port: i32,
}

impl AppMetrics {
    pub fn new(path: String, port: i32) -> AppMetrics {
        AppMetrics { path, port }
    }
}
