/*
 * Tembo Cloud
 *
 * Platform API for Tembo Cloud             </br>             </br>             To find a Tembo Data API, please find it here:             </br>             </br>             [AWS US East 1](https://api.data-1.use1.tembo.io/swagger-ui/)             
 *
 * The version of the OpenAPI document: v1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AppTypeOneOf2 {
    #[serde(rename = "mq-api", deserialize_with = "Option::deserialize")]
    pub mq_api: Option<Box<models::AppConfig>>,
}

impl AppTypeOneOf2 {
    pub fn new(mq_api: Option<models::AppConfig>) -> AppTypeOneOf2 {
        AppTypeOneOf2 {
            mq_api: if let Some(x) = mq_api {Some(Box::new(x))} else {None},
        }
    }
}

