/*
 * Tembo Cloud
 *
 * Platform API for Tembo Cloud             </br>             </br>             To find a Tembo Data API, please find it here:             </br>             </br>             [AWS US East 1](https://api.data-1.use1.tembo.io/swagger-ui/)
 *
 * The version of the OpenAPI document: v1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// AutoStop : AutoStop configures automatic stopping of idle instances. An instance is considered idle if it is more than two days old, hasn't been connected to in over a day, and has not been resumed within the last day. Idle instances are stopped in the time window 9-9:30 AM ET.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AutoStop {
    /// Enable automatic stopping of the instance when idle.
    #[serde(rename = "enabled")]
    pub enabled: bool,
}

impl AutoStop {
    /// AutoStop configures automatic stopping of idle instances. An instance is considered idle if it is more than two days old, hasn't been connected to in over a day, and has not been resumed within the last day. Idle instances are stopped in the time window 9-9:30 AM ET.
    pub fn new(enabled: bool) -> AutoStop {
        AutoStop { enabled }
    }
}
