/*
 * Tembo Cloud
 *
 * Platform API for Tembo Cloud             </br>             </br>             To find a Tembo Data API, please find it here:             </br>             </br>             [AWS US East 1](https://api.data-1.use1.tembo.io/swagger-ui/)             
 *
 * The version of the OpenAPI document: v1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct HistoryPage {
    /// List of historical results
    #[serde(rename = "history")]
    pub history: Vec<models::HistoryEntry>,
    #[serde(rename = "pagination")]
    pub pagination: Box<models::PaginationInfo>,
}

impl HistoryPage {
    pub fn new(history: Vec<models::HistoryEntry>, pagination: models::PaginationInfo) -> HistoryPage {
        HistoryPage {
            history,
            pagination: Box::new(pagination),
        }
    }
}

