/*
 * Tembo Cloud
 *
 * Platform API for Tembo Cloud             </br>             </br>             To find a Tembo Data API, please find it here:             </br>             </br>             [AWS US East 1](https://api.data-1.use1.tembo.io/swagger-ui/)
 *
 * The version of the OpenAPI document: v1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum InstanceEvent {
    #[serde(rename = "restart")]
    Restart,
    #[serde(rename = "stop")]
    Stop,
    #[serde(rename = "start")]
    Start,
}

impl std::fmt::Display for InstanceEvent {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Restart => write!(f, "restart"),
            Self::Stop => write!(f, "stop"),
            Self::Start => write!(f, "start"),
        }
    }
}

impl Default for InstanceEvent {
    fn default() -> InstanceEvent {
        Self::Restart
    }
}
