/*
 * Tembo Cloud
 *
 * Platform API for Tembo Cloud             </br>             </br>             To find a Tembo Data API, please find it here:             </br>             </br>             [AWS US East 1](https://api.data-1.use1.tembo.io/swagger-ui/)
 *
 * The version of the OpenAPI document: v1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum IntOrString {
    IntOrStringOneOf(Box<models::IntOrStringOneOf>),
    IntOrStringOneOf1(Box<models::IntOrStringOneOf1>),
}

impl Default for IntOrString {
    fn default() -> Self {
        Self::IntOrStringOneOf(Default::default())
    }
}
