/*
 * Tembo Cloud
 *
 * Platform API for Tembo Cloud             </br>             </br>             To find a Tembo Data API, please find it here:             </br>             </br>             [AWS US East 1](https://api.data-1.use1.tembo.io/swagger-ui/)             
 *
 * The version of the OpenAPI document: v1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MiddlewareOneOf {
    #[serde(rename = "customRequestHeaders")]
    pub custom_request_headers: Box<models::HeaderConfig>,
}

impl MiddlewareOneOf {
    pub fn new(custom_request_headers: models::HeaderConfig) -> MiddlewareOneOf {
        MiddlewareOneOf {
            custom_request_headers: Box::new(custom_request_headers),
        }
    }
}

