/*
 * Tembo Cloud
 *
 * Platform API for Tembo Cloud             </br>             </br>             To find a Tembo Data API, please find it here:             </br>             </br>             [AWS US East 1](https://api.data-1.use1.tembo.io/swagger-ui/)             
 *
 * The version of the OpenAPI document: v1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// Middleware : Midddleware is used to configure the middleware for the appService. This is specifically configured for the ingress controller Traefik.  Please refer to the example in the `AppService` documentation.
/// Midddleware is used to configure the middleware for the appService. This is specifically configured for the ingress controller Traefik.  Please refer to the example in the `AppService` documentation.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum Middleware {
    MiddlewareOneOf(Box<models::MiddlewareOneOf>),
    MiddlewareOneOf1(Box<models::MiddlewareOneOf1>),
    MiddlewareOneOf2(Box<models::MiddlewareOneOf2>),
}

impl Default for Middleware {
    fn default() -> Self {
        Self::MiddlewareOneOf(Default::default())
    }
}

