/*
 * Tembo Cloud
 *
 * Platform API for Tembo Cloud             </br>             </br>             To find a Tembo Data API, please find it here:             </br>             </br>             [AWS US East 1](https://api.data-1.use1.tembo.io/swagger-ui/)
 *
 * The version of the OpenAPI document: v1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PaginationInfo {
    /// The page returned
    #[serde(rename = "currentPage")]
    pub current_page: i32,
    /// True if more results are available on the next page
    #[serde(rename = "hasMore")]
    pub has_more: bool,
    /// The maximum number of results returned
    #[serde(rename = "limit")]
    pub limit: i32,
}

impl PaginationInfo {
    pub fn new(current_page: i32, has_more: bool, limit: i32) -> PaginationInfo {
        PaginationInfo {
            current_page,
            has_more,
            limit,
        }
    }
}
