/*
 * Tembo Cloud
 *
 * Platform API for Tembo Cloud             </br>             </br>             To find a Tembo Data API, please find it here:             </br>             </br>             [AWS US East 1](https://api.data-1.use1.tembo.io/swagger-ui/)             
 *
 * The version of the OpenAPI document: v1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PatchAutoscaling {
    #[serde(rename = "autostop", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub autostop: Option<Option<Box<models::AutoStop>>>,
    #[serde(rename = "storage", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub storage: Option<Option<Box<models::AutoscalingStorage>>>,
}

impl PatchAutoscaling {
    pub fn new() -> PatchAutoscaling {
        PatchAutoscaling {
            autostop: None,
            storage: None,
        }
    }
}

