/*
 * Tembo Cloud
 *
 * Platform API for Tembo Cloud             </br>             </br>             To find a Tembo Data API, please find it here:             </br>             </br>             [AWS US East 1](https://api.data-1.use1.tembo.io/swagger-ui/)
 *
 * The version of the OpenAPI document: v1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// PgBouncer : PgBouncer is the type for the PGBouncer configuration
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PgBouncer {
    /// Valid pgbouncer parameter values can be found at [https://www.pgbouncer.org/config.html](https://www.pgbouncer.org/config.html)
    #[serde(
        rename = "parameters",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub parameters: Option<Option<std::collections::HashMap<String, String>>>,
    #[serde(rename = "poolMode", skip_serializing_if = "Option::is_none")]
    pub pool_mode: Option<models::PoolerPgbouncerPoolMode>,
    #[serde(
        rename = "resources",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub resources: Option<Option<Box<models::PoolerTemplateSpecContainersResources>>>,
}

impl PgBouncer {
    /// PgBouncer is the type for the PGBouncer configuration
    pub fn new() -> PgBouncer {
        PgBouncer {
            parameters: None,
            pool_mode: None,
            resources: None,
        }
    }
}
