/*
 * Tembo Cloud
 *
 * Platform API for Tembo Cloud             </br>             </br>             To find a Tembo Data API, please find it here:             </br>             </br>             [AWS US East 1](https://api.data-1.use1.tembo.io/swagger-ui/)             
 *
 * The version of the OpenAPI document: v1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PolicyInput {
    /// A valid Action ID. Available Action IDs include 'CreateInstance' and 'ManagePermissions'. Find all available Actions on the Actions API.
    #[serde(rename = "action")]
    pub action: String,
    /// Whether the Action is allowed or not for the Role
    #[serde(rename = "allowed")]
    pub allowed: bool,
    /// A valid Role ID. Available Role IDs include 'admin' and 'basic_member'.
    #[serde(rename = "role")]
    pub role: String,
}

impl PolicyInput {
    pub fn new(action: String, allowed: bool, role: String) -> PolicyInput {
        PolicyInput {
            action,
            allowed,
            role,
        }
    }
}

