/*
 * Tembo Cloud
 *
 * Platform API for Tembo Cloud             </br>             </br>             To find a Tembo Data API, please find it here:             </br>             </br>             [AWS US East 1](https://api.data-1.use1.tembo.io/swagger-ui/)             
 *
 * The version of the OpenAPI document: v1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// PoolerPgbouncerPoolMode : The PgBouncer configuration
/// The PgBouncer configuration
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum PoolerPgbouncerPoolMode {
    #[serde(rename = "session")]
    Session,
    #[serde(rename = "transaction")]
    Transaction,

}

impl std::fmt::Display for PoolerPgbouncerPoolMode {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Session => write!(f, "session"),
            Self::Transaction => write!(f, "transaction"),
        }
    }
}

impl Default for PoolerPgbouncerPoolMode {
    fn default() -> PoolerPgbouncerPoolMode {
        Self::Session
    }
}

