/*
 * Tembo Cloud
 *
 * Platform API for Tembo Cloud             </br>             </br>             To find a Tembo Data API, please find it here:             </br>             </br>             [AWS US East 1](https://api.data-1.use1.tembo.io/swagger-ui/)             
 *
 * The version of the OpenAPI document: v1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// Probes : Probes are used to determine the health of a container. You define this in the same manner as you would for all Kubernetes containers. See the [Kubernetes docs](https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/).
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Probes {
    #[serde(rename = "liveness")]
    pub liveness: Box<models::Probe>,
    #[serde(rename = "readiness")]
    pub readiness: Box<models::Probe>,
}

impl Probes {
    /// Probes are used to determine the health of a container. You define this in the same manner as you would for all Kubernetes containers. See the [Kubernetes docs](https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/).
    pub fn new(liveness: models::Probe, readiness: models::Probe) -> Probes {
        Probes {
            liveness: Box::new(liveness),
            readiness: Box::new(readiness),
        }
    }
}

