/*
 * Tembo Cloud
 *
 * Platform API for Tembo Cloud             </br>             </br>             To find a Tembo Data API, please find it here:             </br>             </br>             [AWS US East 1](https://api.data-1.use1.tembo.io/swagger-ui/)
 *
 * The version of the OpenAPI document: v1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ReplacePathRegexConfigType {
    #[serde(rename = "regex")]
    pub regex: String,
    #[serde(rename = "replacement")]
    pub replacement: String,
}

impl ReplacePathRegexConfigType {
    pub fn new(regex: String, replacement: String) -> ReplacePathRegexConfigType {
        ReplacePathRegexConfigType { regex, replacement }
    }
}
