/*
 * Tembo Cloud
 *
 * Platform API for Tembo Cloud             </br>             </br>             To find a Tembo Data API, please find it here:             </br>             </br>             [AWS US East 1](https://api.data-1.use1.tembo.io/swagger-ui/)             
 *
 * The version of the OpenAPI document: v1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Restore {
    #[serde(rename = "instance_id")]
    pub instance_id: String,
    #[serde(rename = "recovery_target_time", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub recovery_target_time: Option<Option<String>>,
}

impl Restore {
    pub fn new(instance_id: String) -> Restore {
        Restore {
            instance_id,
            recovery_target_time: None,
        }
    }
}

