/*
 * Tembo Cloud
 *
 * Platform API for Tembo Cloud             </br>             </br>             To find a Tembo Data API, please find it here:             </br>             </br>             [AWS US East 1](https://api.data-1.use1.tembo.io/swagger-ui/)
 *
 * The version of the OpenAPI document: v1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SearchResponse {
    /// The file path (in Tembo website repo) to the Tembo document
    #[serde(rename = "file_path")]
    pub file_path: String,
    #[serde(
        rename = "front_matter",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub front_matter: Option<Option<serde_json::Value>>,
    #[serde(rename = "similarity_score")]
    pub similarity_score: f64,
}

impl SearchResponse {
    pub fn new(file_path: String, similarity_score: f64) -> SearchResponse {
        SearchResponse {
            file_path,
            front_matter: None,
            similarity_score,
        }
    }
}
