/*
 * Tembo Cloud
 *
 * Platform API for Tembo Cloud             </br>             </br>             To find a Tembo Data API, please find it here:             </br>             </br>             [AWS US East 1](https://api.data-1.use1.tembo.io/swagger-ui/)
 *
 * The version of the OpenAPI document: v1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct VolumeMount {
    #[serde(rename = "mount_path")]
    pub mount_path: Option<String>,
    #[serde(
        rename = "mount_propagation",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub mount_propagation: Option<Option<String>>,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(
        rename = "read_only",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub read_only: Option<Option<bool>>,
    #[serde(
        rename = "sub_path",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub sub_path: Option<Option<String>>,
    #[serde(
        rename = "sub_path_expr",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub sub_path_expr: Option<Option<String>>,
}

impl VolumeMount {
    pub fn new(mount_path: String, name: String) -> VolumeMount {
        VolumeMount {
            mount_path: Some(mount_path),
            mount_propagation: None,
            name,
            read_only: None,
            sub_path: None,
            sub_path_expr: None,
        }
    }
}
