[test-instance]
environment = "dev"
instance_name = "test-instance"
cpu = "1"
memory = "2Gi"
storage = "10Gi"
replicas = 1
stack_type = "Standard"

[test-instance.postgres_configurations]
shared_preload_libraries = 'pg_stat_statements'
statement_timeout = 60
pg_partman_bgw.dbname = 'postgres'
pg_partman_bgw.interval = "60"
pg_partman_bgw.role = 'postgres'

[test-instance.extensions.pg_jsonschema]
enabled = true
trunk_project = "pg_jsonschema"
trunk_project_version = "0.1.4"

[test-instance.extensions.pgmq]
enabled = true
trunk_project = "pgmq"
trunk_project_version = "0.33.3"

[test-instance.extensions.pg_partman]
enabled = true
trunk_project = "pg_partman"
trunk_project_version = "4.7.4"
