# Values file for the tembo-ai chart with inference gateway component.

inferenceGateway:
  image:
    repository: quay.io/tembo/inference-gateway
    pullPolicy: IfNotPresent
    tag: latest
  serviceAccount:
    create: true
    annotations: {}
  service:
    port: 8080
  resources:
    requests:
      cpu: 100m
      memory: 410Mi
    limits:
      cpu: 1000m
      memory: 512Mi
  securityContext:
    capabilities:
      drop:
      - ALL
    runAsNonRoot: true
    # readOnlyRootFilesystem: true
  autoscaling:
    enabled: true
    minReplicas: 1
    maxReplicas: 5
    # target CPU is a percentage of requests, i.e. the measurement can
    # exceed 100% when limits is greater than requests.
    targetCPUUtilizationPercentage: 99

  nodeSelector: {}
  tolerations: []
  affinity: {}
  podAnnotations: {}
  podSecurityContext: {}
