name: Check crate versions are updated

on:
  pull_request:
    branches:
      - main
      - "release/[0-9]+.[0-9]+"

jobs:
  find_directories:
    name: Find crates that changed
    runs-on: ubuntu-20.04
    outputs:
      changed_crates: ${{ steps.find_directories.outputs.build_matrix }}
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: Find directories including Cargo.toml that changed
        id: find_directories
        uses: ./.github/actions/find-changed-directories
        with:
          contains_the_file: Cargo.toml
          changed_relative_to_branch: ${{ github.base_ref }}

  check_version_not_published:
    name: Check that versions are updated
    runs-on: ubuntu-20.04
    needs:
      - find_directories
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.find_directories.outputs.changed_crates) }}
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: Check this version is not already published
        uses: ./.github/actions/publish-crate
        with:
          working-directory: ${{ matrix.path }}
          dry-run: true
          fail-if-version-published: true
          cargo-registry-token: ${{ secrets.CARGO_REGISTRY_TOKEN }}
