
name: mkdocs CI workflow

defaults:
  run:
    shell: bash
    working-directory: ./

on:
  push:
    branches:
      - main
      - fix-doc-ci
    paths:
      - '.github/workflows/docs.yml'
      - 'docs/**'
      - mkdocs.yml

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - run: curl -sSL https://install.python-poetry.org | POETRY_VERSION=1.2.2 python3 -
      - run: poetry install
      - run: poetry run mkdocs gh-deploy --force
