name: CoreDB operator workflow

defaults:
  run:
    shell: bash
    working-directory: ./coredb-operator/

on:
  pull_request:
    branches:
      - main
    paths:
    - '.github/workflows/operator.yml'
    - 'coredb-operator/**'
  # Always run tests on main or release branches
  push:
    branches:
      - main
      - 'release/**'

jobs:
  lint:
    name: Run linters
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Install minimal nightly with clippy and rustfmt
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          components: rustfmt, clippy
      - uses: Swatinem/rust-cache@v2
        with:
          prefix-key: "coredb-operator-lint"
          workspaces: |
            coredb-operator
      - name: Cargo format
        run: cargo +nightly fmt --check
      - name: Clippy
        run: cargo clippy -- -Dwarnings
  test:
    name: Run unit tests
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: Swatinem/rust-cache@v2
        with:
          prefix-key: "coredb-operator-test"
          workspaces: |
            coredb-operator
      - name: Unit tests
        run: cargo test

  functional_test:
    name: Run functional testing
    runs-on: ubuntu-20.04
    strategy:
      # fail-fast means to cancel all jobs if one fails
      fail-fast: false
      matrix:
        # Go here for a list of versions:
        # https://github.com/kubernetes-sigs/kind/releases
        node_image:
          - 'kindest/node:v1.25.3'
          - 'kindest/node:v1.22.15'
    steps:
      - uses: actions/checkout@v2
      - name: Create k8s Kind Cluster
        uses: helm/kind-action@v1.5.0
        with:
          node_image: ${{ matrix.node_image }}
      - name: Apply safety check label to namespace
        run: |
          kubectl label namespace default safe-to-run-coredb-tests=true
          kubectl get -o yaml namespaces
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: Swatinem/rust-cache@v2
        with:
          prefix-key: "coredb-operator-functional-test"
          workspaces: |
            coredb-operator
      - name: Check CRD is updated in the yaml directory
        run: |
          set -xe
          cargo run --bin crdgen > yaml/crd.yaml
          git diff --exit-code yaml/crd.yaml
      - name: Run functional / integration tests
        run: |
          set -xe
          # Install the CRD
          cargo run --bin crdgen | kubectl apply -f -
          kubectl get crds
          # Start the operator in the background
          cargo run &
          # Run the tests
          cargo test -- --ignored --nocapture
      - name: Debugging information
        if: always()
        run: |
          set +e
          set -x
          echo "=========="
          kubectl get pods --all-namespaces
          echo "=========="
          kubectl get -o yaml sts
          echo "=========="
          kubectl get -o yaml svc
          echo "=========="
          kubectl get -o yaml pods
          echo "=========="
          kubectl get -o yaml coredb
          echo "=========="
