name: CoreDB prerelease workflow

# On push to main branch, we prepare a prerelease.
# If there is already a prerelease, then we replace
# that with a new prerelease.
#
# When the team is ready to release, we promote the
# prerelease to a release. Then the release.yml workflow
# will run to publish the release.

on:
  push:
    branches:
      - main

jobs:
  build_and_push_images:
    name: Build and push images
    runs-on: ubuntu-20.04
    strategy:
      # fail-fast means to cancel all jobs if one fails
      fail-fast: false
      matrix:
        include:
          - name: coredb-operator
            path: ./coredb-operator
          - name: postgres
            path: ./postgres
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: Build and upload image
        uses: ./.github/actions/build-and-push-to-quay
        with:
          image_name: ${{ matrix.name }}
          docker_directory: ${{ matrix.path }}
          tags: main
          publish_calver: true
          calver_suffix: "-prerelease"
          quay_user: ${{ secrets.QUAY_USER }}
          quay_password: ${{ secrets.QUAY_PASSWORD }}
