name: Generate and Deploy Documentation

on:
  push:
    paths:
      - 'tembo-cli/**'
    branches:
      - main
  pull_request:
    paths:
      - 'tembo-cli/**'
    branches:
      - main
      - develop
      - feature/*

jobs:
  generate_docs:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v4
        - name: Install system dependencies
          run: |
            set -xe
            sudo apt-get update

        - name: Generate and Deploy Docs
          uses: ./.github/actions/generate-docs
          with:
            repository: 'tembo-io/website'
            ssh_key: ${{ secrets.SERVICE_USER_GITHUB_SSH_KEY }}
            branch: 'plat-410'
