name: Trunk CLI workflow

defaults:
  run:
    shell: bash
    working-directory: ./trunk/cli/

on:
  pull_request:
    branches:
      - main
      - 'release/**'
    paths:
    - '.github/workflows/trunk-cli.yml'
    - 'trunk/cli/**'
  # Always run tests on main or release branches
  push:
    branches:
      - main
      - 'release/**'

jobs:
  lint:
    name: Run linters
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Install minimal nightly with clippy and rustfmt
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          components: rustfmt, clippy
      - uses: Swatinem/rust-cache@v2
        with:
          prefix-key: "trunk-cli-lint"
          workspaces: |
            trunk/cli
      - name: Cargo format
        run: cargo +nightly fmt --check
      - name: Clippy
        run: cargo clippy

  test:
    name: Run tests
    runs-on:
      - self-hosted
      - dind
      - large-8x8
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: Swatinem/rust-cache@v2
        with:
          prefix-key: "trunk-cli-functional-test"
          workspaces: |
            trunk/cli
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y pkg-config libssl-dev postgresql
      - name: Run functional tests
        run: |
          cargo test -- --nocapture
