name: Trunk registry workflow

defaults:
  run:
    shell: bash
    working-directory: ./trunk/registry/

on:
  pull_request:
    branches:
      - main
    paths:
      - '.github/workflows/trunk-registry.yml'
      - 'trunk/registry/**'

  # Always run on main or release branches
  push:
    branches:
      - main
      - release**

# Required for sqlx query!() macro used in registry code.
# See https://docs.rs/sqlx/0.6.2/sqlx/macro.query.html#requirements for more info.
env:
  DATABASE_URL: ${{ secrets.TRUNK_REGISTRY_DEV_DB_URL }}

jobs:
  lint:
    name: Run linters
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Install minimal nightly with clippy and rustfmt
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          components: rustfmt, clippy
      - uses: Swatinem/rust-cache@v2
        with:
          prefix-key: "lint"
      - name: Cargo format
        run: cargo +nightly fmt --all --check
      - name: Clippy
        run: cargo clippy -- -Dwarnings
  build-push:
    name: Build and push image
    runs-on: ubuntu-20.04
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: Set version strings
        id: versions
        run: |
          echo "SHORT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
      - name: Build image
        run: |
          export DATABASE_URL={{ secrets.TRUNK_REGISTRY_DEV_DB_URL }}
          set -xe
          docker build -t pgtrunkio-backend .
          docker tag pgtrunkio-backend pgtrunkio-backend:latest
          docker tag pgtrunkio-backend pgtrunkio-backend:${{ steps.versions.outputs.SHORT_SHA }}
      - name: Push To quay.io
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: redhat-actions/push-to-registry@v2
        with:
          registry: quay.io/coredb
          image: pgtrunkio-backend
          tags: latest ${{ steps.versions.outputs.SHORT_SHA }}
          username: ${{ secrets.QUAY_USER }}
          password: ${{ secrets.QUAY_PASSWORD }}